guard 'sass', :input => 'source/sass', :output => 'compiled/css'
guard 'coffeescript', :input => 'source/coffeescript', :output => 'compiled/js'

guard 'process', :name => 'minify-css', :command => 'juicer merge compiled/css/all.css -o compiled/css/all.min.css --force -s' do
  watch /^compiled\/css\/all.css/
end

guard 'process', :name => 'minify-js', :command => 'juicer merge compiled/js/all.js -o compiled/js/all.min.js --force -s' do
  watch /^compiled\/js\/all.js/
end
